### ISSUE TITLE
[FEAT] Gift VIP to other users

### ISSUE THREAD

**Issue by robbmanes** [robbmanes/seeding-reward-bot#19]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to give VIP to other users acquired through seeding.  There should be a command to allow for this.

**Describe the solution you'd like**
Some command, like `/hll gift`, etc, should allow you to do this.

**Comment by andrewferguson343** [comment]
@robbmanes I think I have this sorted out, do you have a link for setting up rcon locally to test it out

**Comment by andrewferguson343** [comment]
Initial PR is in #25, but there is still some work to be done based on the above comment

**Comment by robbmanes** [comment]
Fixed, thanks!
